# Generated by Django 2.2 on 2019-12-23 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsEmailFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recipient', models.EmailField(max_length=254, verbose_name='E-mail уведомлений')),
                ('email_from', models.EmailField(max_length=254, verbose_name='E-mail исходящий')),
            ],
            options={
                'verbose_name': 'Настройка отправки E-mail',
                'verbose_name_plural': 'Настройка отправки E-mail',
            },
        ),
        migrations.CreateModel(
            name='SpecificationsFeedback2Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('select_forms', models.TextField(blank=True, null=True, verbose_name='Данные с форм выбора')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Landing', verbose_name='Лендинг')),
            ],
            options={
                'verbose_name': 'Форму с характеристиками',
                'verbose_name_plural': 'Форма с характеристиками',
            },
        ),
        migrations.CreateModel(
            name='SimpleFeedback2Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('checkbox_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Выбранные чекбоксы')),
                ('type_form', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Приветствие'), (4, 'Каталог'), (9, 'Форма дополнительных предложений'), (8, 'Программа финансирования'), (100, 'Продукт')], null=True, verbose_name='Тип формы')),
                ('characteristic', models.TextField(blank=True, null=True, verbose_name='Характеристики')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('name_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Продукт')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Landing', verbose_name='Лендинг')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailFeedback2Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Landing', verbose_name='Лендинг')),
            ],
            options={
                'verbose_name': 'Форма с e-mail',
                'verbose_name_plural': 'Форма с e-mail',
            },
        ),
        migrations.CreateModel(
            name='ManagerEmailFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_form', models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (4, 'Каталог'), (9, 'Форма дополнительных предложений'), (8, 'Программа финансирования'), (100, 'Продукт'), (5, 'Форма с характеристиками')], verbose_name='Тип формы')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Landing', verbose_name='Лендинг')),
                ('settings_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.SettingsEmailFeedback')),
            ],
            options={
                'verbose_name': 'Е-mail менеджера',
                'verbose_name_plural': 'Е-mail менеджеров',
                'unique_together': {('landing', 'type_form')},
            },
        ),
    ]
